import React, { useEffect, useState } from 'react';
import api from '../../services/api';

export default function CareerReport() {
  const [report, setReport] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { api.get('/reports/student-report').then(({ data }) => setReport(data)).catch((e) => setError(e.response?.data?.error || 'Could not load your report.')); }, []);

  if (error) return <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</div>;
  if (!report) return <p className="py-10 text-center text-sm text-slate-500">Loading career report…</p>;
  const totals = report.totals || {};
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Career portfolio</p><h1 className="mt-1 text-2xl font-bold text-slate-900">My career report</h1><p className="mt-1 text-sm text-slate-500">{report.student.name} · {report.student.college} · {report.student.department}</p></div><button onClick={() => window.print()} className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-900">Print / save PDF</button></header>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['Applications', totals.applications], ['Selected', totals.selected], ['Skills', totals.skills], ['Certifications', totals.certifications], ['Projects', totals.projects]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value ?? 0}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold text-slate-900">Application history</h2></div>{report.applications.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Opportunity</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Match</th><th className="px-4 py-3">Applied</th></tr></thead><tbody className="divide-y divide-slate-100">{report.applications.map((item) => <tr key={item.id}><td className="px-4 py-3 font-medium">{item.opportunity}</td><td className="px-4 py-3">{item.company}</td><td className="px-4 py-3">{item.type}</td><td className="px-4 py-3">{item.status.replaceAll('_', ' ')}</td><td className="px-4 py-3">{Number(item.matchScore || 0)}%</td><td className="px-4 py-3">{new Date(item.appliedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-slate-500">No opportunity applications recorded yet.</p>}</section>
    <div className="grid gap-4 md:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Skills</h2>{report.skillProfile.length ? <div className="mt-3 flex flex-wrap gap-2">{report.skillProfile.map((item) => <span key={item.name} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-800">{item.name} · {item.level}</span>)}</div> : <p className="mt-2 text-sm text-slate-500">Add skills to build your profile.</p>}</section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Certifications</h2>{report.certifications.length ? <ul className="mt-2 list-inside list-disc space-y-1 text-sm text-slate-700">{report.certifications.map((item) => <li key={item.id}>{item.name}</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No certifications recorded yet.</p>}</section></div>
  </div>;
}
