/**
 * Section 3 & 30: Role & Permission Matrix
 * Granular permissions mapped to all 10 user types.
 * Allows adding new roles and permissions dynamically.
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  COLLEGE_ADMIN: 'COLLEGE_ADMIN',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  FACULTY_COORDINATOR: 'FACULTY_COORDINATOR',
  STUDENT: 'STUDENT',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  COMPANY_RECRUITER: 'COMPANY_RECRUITER',
  SKILL_PROVIDER: 'SKILL_PROVIDER',
  MENTOR: 'MENTOR',
};

const PERMISSIONS = {
  // User Management
  USER_CREATE: 'USER_CREATE',
  USER_VIEW: 'USER_VIEW',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_MANAGE: 'USER_MANAGE',
  USER_STATUS_TOGGLE: 'USER_STATUS_TOGGLE', // Activate/Deactivate
  ROLE_MANAGE: 'ROLE_MANAGE',

  // College & Department
  COLLEGE_MANAGE: 'COLLEGE_MANAGE',
  COLLEGE_VIEW: 'COLLEGE_VIEW',
  DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',

  // Student Profiles
  STUDENT_PROFILE_VIEW: 'STUDENT_PROFILE_VIEW',
  STUDENT_PROFILE_EDIT: 'STUDENT_PROFILE_EDIT',
  STUDENT_ALL_VIEW: 'STUDENT_ALL_VIEW',
  STUDENT_ACADEMIC_APPROVE: 'STUDENT_ACADEMIC_APPROVE',

  // Company & Recruitment
  COMPANY_MANAGE: 'COMPANY_MANAGE',
  COMPANY_VERIFY: 'COMPANY_VERIFY',
  OPPORTUNITY_CREATE: 'OPPORTUNITY_CREATE',
  OPPORTUNITY_VIEW: 'OPPORTUNITY_VIEW',
  OPPORTUNITY_APPROVE: 'OPPORTUNITY_APPROVE',
  APPLICATION_VIEW: 'APPLICATION_VIEW',
  APPLICATION_UPDATE: 'APPLICATION_UPDATE', // Shortlist, Interview, Hire
  OFFER_ISSUE: 'OFFER_ISSUE',

  // Skill Hub
  SKILL_CREATE: 'SKILL_CREATE',
  SKILL_PROGRAM_PUBLISH: 'SKILL_PROGRAM_PUBLISH',
  SKILL_VERIFY: 'SKILL_VERIFY',
  SKILL_MATCH_RUN: 'SKILL_MATCH_RUN',

  // Mentorship & Progress
  MENTORSHIP_ASSIGN: 'MENTORSHIP_ASSIGN',
  MENTORSHIP_FEEDBACK: 'MENTORSHIP_FEEDBACK',

  // Reports & Logs
  REPORT_VIEW_ALL: 'REPORT_VIEW_ALL',
  REPORT_VIEW_COLLEGE: 'REPORT_VIEW_COLLEGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
};

// Default mapping for each role
const ROLE_PERMISSIONS_MAP = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // All permissions

  [ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_STATUS_TOGGLE,
    PERMISSIONS.COLLEGE_MANAGE,
    PERMISSIONS.COLLEGE_VIEW,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.COMPANY_VERIFY,
    PERMISSIONS.OPPORTUNITY_APPROVE,
    PERMISSIONS.STUDENT_ALL_VIEW,
    PERMISSIONS.REPORT_VIEW_ALL,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],

  [ROLES.COLLEGE_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.COLLEGE_VIEW,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.STUDENT_ALL_VIEW,
    PERMISSIONS.STUDENT_ACADEMIC_APPROVE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.REPORT_VIEW_COLLEGE,
  ],

  [ROLES.DEPARTMENT_ADMIN]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.COLLEGE_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.STUDENT_ALL_VIEW,
    PERMISSIONS.STUDENT_ACADEMIC_APPROVE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.REPORT_VIEW_COLLEGE,
  ],

  [ROLES.FACULTY_COORDINATOR]: [
    PERMISSIONS.COLLEGE_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.STUDENT_ALL_VIEW,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.MENTORSHIP_FEEDBACK,
    PERMISSIONS.REPORT_VIEW_COLLEGE,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.STUDENT_PROFILE_VIEW,
    PERMISSIONS.STUDENT_PROFILE_EDIT,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.SKILL_MATCH_RUN,
  ],

  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.OPPORTUNITY_CREATE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.OFFER_ISSUE,
    PERMISSIONS.STUDENT_PROFILE_VIEW,
  ],

  [ROLES.COMPANY_RECRUITER]: [
    PERMISSIONS.OPPORTUNITY_CREATE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.STUDENT_PROFILE_VIEW,
  ],

  [ROLES.SKILL_PROVIDER]: [
    PERMISSIONS.SKILL_PROGRAM_PUBLISH,
    PERMISSIONS.SKILL_VERIFY,
    PERMISSIONS.SKILL_CREATE,
  ],

  [ROLES.MENTOR]: [
    PERMISSIONS.STUDENT_PROFILE_VIEW,
    PERMISSIONS.MENTORSHIP_FEEDBACK,
  ],
};

function hasPermission(role, requiredPermission) {
  const permissions = ROLE_PERMISSIONS_MAP[role] || [];
  return permissions.includes(requiredPermission);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS_MAP,
  hasPermission,
};
